In [47]:
#Q1

import numpy as np
#part a
a = np.random.randint(1,21, size=15)
b = a.reshape(3, 5)
print(b)
#part b
b.shape
#part c
for i in range (3):
  maxIndex=np.argmax(b[i])
  b[i,maxIndex]=0
print(b)


[[12  4  8  4 16]
 [19  8 10 13 18]
 [19 15 20  9 17]]
[[12  4  8  4  0]
 [ 0  8 10 13 18]
 [19 15  0  9 17]]


In [9]:
#Q2
x = np.array([[2, 4, 6], [7, 9, 11]], np.int32)
print(type(x))
print(x.shape)
print(x.dtype)

<class 'numpy.ndarray'>
(2, 3)
int32


In [31]:
#Q3
array=[[0, 1, 2],
[3, 4, 5]]
trace = np.trace(array)

print("\n sum of given 3X3 arrays:")
print(trace)


 sum of given 3X3 arrays:
4


In [38]:
#Q4
#part a
array=np.arange(10,71)
print("Array of all the  integers from 10 to 70")
print(array)
 #part b
x = np.array([[6,8],[12,14]])
y = np.array([[5,6],[7,8]])
print(np.sum(x))
print(np.subtract(x, y))
print(np.sqrt(x))

#part c
array3 = [[5.54, 3.38, 7.99],
 [3.54, 4.38, 6.99],
 [1.54, 2.39, 9.29]]
print("\n Sort the said array by row in ascending order:")
print(np.sort(array3))
print("\n Sort the said array by column in ascending order:")
print(np.sort(array3, axis=0))

Array of all the  integers from 10 to 70
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70]
40
[[1 2]
 [5 6]]
[[2.44948974 2.82842712]
 [3.46410162 3.74165739]]

 Sort the said array by row in ascending order:
[[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]

 Sort the said array by column in ascending order:
[[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]


In [40]:
#Q5
import numpy as np
Array = [[4, 2, np.nan, 1],
[11, 12, 14, 9],
 [5, np.nan, 1, np.nan]]
print(np.isnan(Array))

[[False False  True False]
 [False False False False]
 [False  True False  True]]
